from utils.url_features import extract_url_features, get_feature_vector, get_rule_based_score as url_rule_score, highlight_url_parts
from utils.text_features import extract_text_features, get_rule_based_score as text_rule_score, detect_input_type, highlight_text_spans
